package com.example.calcolatorefire.domain;

public enum CalculationErrorCode {
    INVALID_AGE_ORDER,
    INVALID_FIRE_DURATION,
    INVALID_RATE,
    INVALID_SWR,
    INVALID_AMOUNT,
    INVALID_METHOD,
    INVALID_RESOURCE,
    INVALID_RESOURCE_PERIOD,
    INVALID_CAPITAL_GAINS_TAX_RATE,
    INVALID_STAMP_DUTY_RATE,
    INVALID_TAX_BASIS,
    FISCAL_SOLUTION_NOT_FOUND,
    UNREACHABLE_WITH_ZERO_MONTHS
}
